import Link from 'next/link'
import { CheckCircle2, MapPin, Star, ShieldCheck } from 'lucide-react'
import type { Artisan } from '@/types/artisan'
import { tradeBySlug } from '@/data/trades'

export function ArtisanCard({ artisan }: { artisan: Artisan }) {
  const trade = tradeBySlug[artisan.trade]
  return <article className="overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm transition-shadow duration-200 hover:shadow-md"><Link href={`/artisans/${artisan.id}`} className="block"><div className="relative h-44 overflow-hidden bg-stone-100"><img src={artisan.coverImage} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1 text-xs font-semibold text-slate-900">{trade.label}</div></div><div className="px-5 pb-5"><div className="-mt-10 flex items-end justify-between"><img src={artisan.photo} alt={artisan.name} className="h-20 w-20 rounded-xl border-4 border-white object-cover shadow-sm"/><div className="mb-1 flex items-center gap-1 text-sm font-bold text-slate-900"><Star size={16} className="fill-amber-500 text-amber-500"/>{artisan.rating.toFixed(1)} <span className="font-normal text-stone-500">({artisan.reviewCount})</span></div></div><div className="mt-3"><div className="flex items-center gap-2"><h3 className="font-bold text-slate-900">{artisan.name}</h3>{artisan.verified && <CheckCircle2 size={17} className="text-blue-600"/>}</div><p className="mt-0.5 text-sm font-medium text-stone-600">{artisan.businessName}</p><p className="mt-3 flex items-center gap-1.5 text-sm text-stone-500"><MapPin size={15}/>{artisan.city}</p><p className="mt-3 line-clamp-2 text-sm leading-6 text-stone-600">{artisan.shortBio}</p></div><div className="mt-5 flex items-center justify-between border-t border-stone-100 pt-4"><span className="flex items-center gap-1.5 text-xs font-medium text-stone-600"><ShieldCheck size={15} className="text-emerald-600"/> Insured &amp; verified</span><span className="text-sm font-semibold text-amber-700">View profile</span></div></div></Link></article>
}
